# Generated by Django 5.2.4 on 2026-08-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_seed_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rate_per_night',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='rate',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
