# Generated by Django 5.2.4 on 2026-08-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_booking_rate_per_night_alter_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('due', 'Due'), ('paid', 'Paid')], default='due', max_length=10),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('members', models.PositiveIntegerField(default=1)),
                ('rate_per_person', models.DecimalField(decimal_places=0, max_digits=10)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('status', models.CharField(choices=[('checked_in', 'Checked in'), ('checked_out', 'Checked out')], default='checked_in', max_length=20)),
                ('payment_status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid')], default='due', max_length=10)),
                ('rooms', models.ManyToManyField(blank=True, related_name='groups', to='main_app.room')),
            ],
            options={
                'ordering': ['status', '-check_in'],
            },
        ),
    ]
