# Generated by Django 5.2.4 on 2026-08-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('room_maintenance', 'Room maintenance'), ('garden_cleaning', 'Garden cleaning'), ('repairing', 'Repairing'), ('other', 'Other')], default='room_maintenance', max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Maintenance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
